package com.github.yqy7.puppeteer4jvm

/**
 *  @author qiyun.yqy
 *  @date 2018/10/19
 */
const val PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD"
const val PUPPETEER_DOWNLOAD_HOST = "PUPPETEER_DOWNLOAD_HOST"
const val PUPPETEER_DOWNLOAD_FOLDER = "PUPPETEER_DOWNLOAD_FOLDER"
const val PUPPETEER_CHROMIUM_REVISION = "PUPPETEER_CHROMIUM_REVISION"